services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./grate-sqlserver/init-db:/docker-entrypoint-initdb.d
volumes:
  mariadb_data:
    driver: local
  postgres_data:
    driver: local
  sqlserver-data:
    driver: local
