USE mydb;
GO

CREATE TABLE Users (
Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE Courses (
Id INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE Chapters (
Id INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE UserCourses (
UserId INT NOT NULL,
CourseId INT NOT NULL,
PRIMARY KEY (UserId, CourseId),
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE
);
GO

CREATE TABLE CourseChapters (
CourseId INT NOT NULL,
ChapterId INT NOT NULL,
PRIMARY KEY (CourseId, ChapterId),
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE,
FOREIGN KEY (ChapterId) REFERENCES Chapters(Id) ON DELETE CASCADE
);
GO
