version: "3"
services:
  ddb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: ddb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  ddb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: ddb-admin
    environment:
      - DYNAMO_ENDPOINT=ddb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - ddb-local
