version: "3"
services:
  pgsql:
    image: postgres:14
    platform: linux/x86-64
    tty: true
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "||", "exit", "1" ]
      interval: 2s
      timeout: 3s
      retries: 2
  backend:
    container_name: net-app
    expose:
      - 80
      - 443
    image: final:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - net-net
    depends_on:
      - pgsql

networks:
  net-net:
    driver: bridge
