-- Usersテーブルの作成
CREATE TABLE Users (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL
);

-- Coursesテーブルの作成
CREATE TABLE Courses (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Title TEXT NOT NULL
);

-- Chaptersテーブルの作成
CREATE TABLE Chapters (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Title TEXT NOT NULL
);

-- UserCoursesテーブルの作成
CREATE TABLE UserCourses (
UserId INTEGER NOT NULL,
CourseId INTEGER NOT NULL,
PRIMARY KEY (UserId, CourseId),
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE
);

-- CourseChaptersテーブルの作成
CREATE TABLE CourseChapters (
CourseId INTEGER NOT NULL,
ChapterId INTEGER NOT NULL,
PRIMARY KEY (CourseId, ChapterId),
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE,
FOREIGN KEY (ChapterId) REFERENCES Chapters(Id) ON DELETE CASCADE
);
