CREATE TABLE Users (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL
);

CREATE TABLE Courses (
Id INT AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(255) NOT NULL
);

CREATE TABLE Chapters (
Id INT AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(255) NOT NULL
);

CREATE TABLE UserCourses (
UserId INT NOT NULL,
CourseId INT NOT NULL,
PRIMARY KEY (UserId, CourseId),
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE
);

CREATE TABLE CourseChapters (
CourseId INT NOT NULL,
ChapterId INT NOT NULL,
PRIMARY KEY (CourseId, ChapterId),
FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE,
FOREIGN KEY (ChapterId) REFERENCES Chapters(Id) ON DELETE CASCADE
);
